### ISSUE TITLE
Add option to define canvas sizes

### ISSUE THREAD

**Issue by smeijer** [slothking-online/diagram#71]
The dimensions of the canvas, are currently extracted from `document.body`. This makes it impossible to nest the canvas in a page layout, with for example a navbar, sidebar, or other elements. Sometimes, we just don't want the thing to be "fullscreen".

https://github.com/slothking-online/diagram/blob/eec54166c5a44de0b3d6208839af82e2c9dc2405/src/Diagram/index.ts#L113

It would be nice if we could provide a `width` and `height` to it. Or can we not simply extract the dimensions from `domElement` instead of `document.body`?

https://github.com/slothking-online/diagram/blob/eec54166c5a44de0b3d6208839af82e2c9dc2405/src/Diagram/index.ts#L95

**Comment by aexol** [comment]
It works the other way. We extract only at the beginning to create canvas then we resize. Canvas is complicated componenent to work with DOM. Right now you have public diagram resize method so after you create diagram inside div with for example `width` and `height` you call diagram.resize() and it will autoresize to the parent component. Can you check this?

**Comment by aexol** [comment]
BTW I am open for contributions :)

**Comment by hzub** [comment]
@smeijer @aexol 
As a fan of flexibility - I'd make it universal and provide two mechanisms:
1) Explicitly set `width` and `height`
OR
2) Periodic watcher of underlying's element size that will automatically set width/height. (e.g. mechanism similar to http://marcj.github.io/css-element-queries/)

**Comment by aexol** [comment]
@hzub Can you check if it works with canvas?. Implementation that I have prevents canvas from resizing parent element.

**Comment by smeijer** [comment]
Awesome! It does work.


```js
componentDidMount() {
  this.diagram.resize();
}
```

Thanks for the fast response.

@hzub, The watcher would be possible. But the question is if it's the responsibility of this library. It does make sense if `diagram` requires an explicit width in pixels because then we would need to listen to ~document~ element resize events.

I would say; as soon as the user provides the `width` and `height` explicitly, there is no reason to listen to anything. And this could simplify it a lot. Just make `width` and `height` required attributes.

`react-virtualized` has required dimension attributes as well; I've never experienced that as a problem.

Actually; I have quite a lot of references to [`react-resize-detector`](https://www.npmjs.com/package/react-resize-detector) in my code base, and don't see it as a problem. I like that child components just scale to 100%, unless specified otherwise.

Example usage with `react-resize-detector`

```jsx
<ReactResizeDetector handleWidth handleHeight>
  {(width, height) => (
    <Diagram width={width} height={height} />
  )}
</ReactResizeDetector>
```

**Comment by aexol** [comment]
Great Library - I couldn't find anything like that myself. I can't add this to diagram though as it is not react dependent. Anyway thanks! @smeijer  @hzub

**Comment by hzub** [comment]
@smeijer I agree, it shouldn't be responsibility of this library at all - but it would be reasonable to add this kind of solution to the README.

**Comment by smeijer** [comment]
Yeah, I'm trying to figure out a few things myself. I'll definitely contribute by writing some docs, when I have something nice working here.

@aexol, you're quite a fast responder. Do you think it's okay to collect small questions here on github? Or is it an idea to create a community on spectrum for example?

Simple things like the sizes problem. Or the "how do I listen to events" (#72) can help a lot to get some traction.

**Comment by aexol** [comment]
@smeijer we can definitely create spectrum. I am not experienced in using it but I can learn. Having a knowledge base it is always a good thing

**Comment by hzub** [comment]
Done in https://github.com/slothking-online/diagram/pull/80
`Diagram` class now consumes optional `options` parameter, which includes:
```
width: number | undefined;
height: number | undefined;
autosizeWatcher: boolean;
autosizeInterval: number;
autosizeOnWindowResize: boolean,
```
We can either turn on/off autoresizing on interval and window resize, also it's possible to explicitly set width and height. Also, there is a method named `resize()` in `Diagram` class that make diagram class resizing possible.
