### ISSUE TITLE
Add option to allow custom id generator

### ISSUE THREAD

**Issue by smeijer** [slothking-online/diagram#73]
It would be nice if we could add our custom id generator, to generate node id's instead of the provided `uuidv4`.

That way we could use [`picoid`](https://github.com/smeijer/picoid) or [`nanoid`](https://github.com/ai/nanoid) or anything else to match existing application ids.

```js
const picoid = require('picoid');

const diagram = new Diagram('#id', {
  generateId: () => picoid(5),
});
```

```bash
uuidv4:    c57274f1-536c-4fb7-a645-82c828ad37b1
picoid:    oRnKm4kBQ5Z2Qe4hh
picoid(5): y98Cp
```

**Comment by hzub** [comment]
Done in #80
`Diagram` class now consumes optional options parameter, which includes `generateIdFn: () => string` field.
