### ISSUE TITLE
Return false from onConnect opens context menu on mouse up

### ISSUE THREAD

**Issue by smeijer** [slothking-online/diagram#77]
When returning false from the `connectionFunction`, to prevent the link from being created. The context menu is shown on mouse up.

The `onConnect` below prevents self-referencing links, and to have more than 1 outgoing link:

```js
function onConnect(input, output ) {
  if (input.id === output.id) {
    return false;
  }

  return output.outputs.length === 0;
}

const diagram = new Diagram('#id', defaultTheme, onConnect);
```

![graphsource-onconnect](https://user-images.githubusercontent.com/1196524/53512354-d69a1780-3ac2-11e9-88d4-f1634a12ab68.gif)

**Comment by hzub** [comment]
Fixed in #81.
